### ISSUE TITLE
Return more details in invalid signature error

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#1005]
## Rationale

Hermez Protocol signature is not ECDSA standard. It follows EIP712 and it has some parameters. Today when a signature is invalid the user does not know which parameters are stored in the node. This is issue is to return more information regarding EIP-712 a hermez node is using to allow the user to know how to correctly build a signature to hermez node

Suggest to change the common/accountcreationauths.go/VerifySignature method to return true and false and an error with the details.

**Comment by ARR552** [comment]
Implemented in PR #1006
