### ISSUE TITLE
Hermez own price provider

### ISSUE THREAD

**Issue by tclemos** [hermeznetwork/hermez-node#1007]
## Rationale

Create a `hermez price provider` to work as a fallback in case other providers fail or do not have the token registered yet.

Today we have 6 memecoins created by Hermez to support the Paris EthCC event, the current price providers do not have prices for them and this is causing a lot of `unnecessary` error messages in the `hermez-node` log.

Having a hermez price provider, we could provide prices for these tokens instead of failing to retrieve them, also we could work as a fallback for any other token in the network, in case all other providers are unreachable for some reason.

## Implementation

Since the price updater is being isolated in a new service and the new implementation will be compatible with multiple providers, it should be straightforward to add a new provider like any other, it can be as simple as providing data from a config file with tokens and prices in key/value pair structure like `CORGI=10` `LAMBO=5.5`

**Comment by jeffprestes** [comment]
@marioidival is working on this creating a micro service to provide price to tokens included at hermez smart contract rollup

**Comment by marioidival** [comment]
@jeffprestes The main idea from @tclemos is: we be a price provider like bitfinex or uniswap, but focus in meme tokens.

**Comment by jeffprestes** [comment]
For this we can define static values for the token in priceUpdater service.

**Comment by marioidival** [comment]
Yes, I had talked with him about this, @jeffprestes :D
