### ISSUE TITLE
Change check gasPrice model to fit EIP-1559 spec

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#1014]
## Rationale

To be fully compliant with Ethereum London fork, Hermez node might need to change how to get from Ethereum node the BaseGasPrice fee and check how much tip it's going to need to send to miner.

## Implementation

Please review the EIP-1559 spec and also this issue for more information: https://github.com/hermeznetwork/integration-testing/issues/451

**Comment by mfcastellani** [comment]
Cool article about the problem: https://www.financemagnates.com/cryptocurrency/news/is-eip-1559-make-or-break-for-ethereums-future/

**Comment by mfcastellani** [comment]
Relevant links:

- https://github.com/ethereum/go-ethereum/pull/22837 
- https://github.com/ethereum/go-ethereum/pull/22888/files
- https://github.com/ethereum/go-ethereum/pull/22970/files
