### ISSUE TITLE
Document in gitflow extra layer features

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#1018]
## Rationale

Some times a feature takes a lot of time to reach a functional state, and doing small PRs to `develop` feels bad since it forces us to either do releases with uncompleted features or block the release flow.

In this scenarios we've been adding a extra layer of branches, but this is not documented. Also I'd line to introduce a way of doing this: have a dedicated name for this extra branches:

- Normal case `develop` <== `feature/xxx`
- Long feature case: `develop` <== `feature/xxx` <== `XXX/yyy`. As example: `develop` <== `feature/coordinators-network` <== `coordnet/add-eedge-test`

**Comment by jeffprestes** [comment]
It looks good to me. I just have a small suggestion: we should use the feature name in the small extra branch. I mean: `develop <== feature/coordinators-network <== feature/coordinators-network/add-eedge-test` this way will become easily to visualize this small feature branch belongs to the long feature case.

**Comment by marioidival** [comment]
I don't like the suggestion of @jeffprestes, the name branches will be huge!
To figure out that branch belongs to the long feature can be saw there -> 

![Screen Shot 2021-07-21 at 10 28 41](https://user-images.githubusercontent.com/1129263/126496703-8b07421f-8ed7-4463-a4d7-7a11d14afdcd.png)

**Comment by jeffprestes** [comment]
@marioidival I am sorry but I don't think it is a problem and also it avoids another problem. 
The way you say it we can check the value using Github value easily and that's right but if we list the branch in terminal is not clear for what that branch belongs to. 
It can or cannot be long but I don't think they will become huge and besides that clear names helps to avoid confusion and bugs. **Communication is key**

**Comment by arnaubennassar** [comment]
TBH for me both things work, but I think that `coordnet/wan-discovery` looks better than `feature/coordinators-network/wan-discovery` and it's as clear in what represents as the other option. 

But again, I think this is the kind of thing that it's very easy to have strong opinions on, so maybe best option is to vote?
