### ISSUE TITLE
Forging empty batches in Testnet

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#1038]
## Summary of Bug

Bootcoordinator in Testnet / Rinkeby is forging empty batches (batches with no transactions on it) . But the config is defined to not forge it

### Expected Behavior

No forging empty batches.

### Steps to Reproduce

Setup a hermez node in testnet, use the same config file and monitoring it.

**Comment by tclemos** [comment]
This is the result of the investigation for this problem:
- boot coordinator was not forging batches
- when the slot owner does not forge batches, anyone can forge
- another node in the network with configuration to forge batches without tx was forging

TLDR: this is not a bug, it's a feature! 😄
