### ISSUE TITLE
Update tx by account idx and nonce

### ISSUE THREAD

**Issue by Mikelle** [hermeznetwork/hermez-node#1066]
## Rationale
Right now we cannot update the amount or fee in tx, bcs those fields are taking part in transactionID creation, so if the transaction is stuck bcs of the low fee, it will be stuck for a long time.

## Implementation

Add new endpoint: `PUT /transactions-pool/accounts/:idx/nonces/:nonce`. So the expected behavior will be:
1. Find tx in the pool by account idx and nonce.
2. Delete found tx and add a new one from the request
3. Return new transactionID

**Comment by jeffprestes** [comment]
It would add one more checking: the transaction state needs to be in pending mode, it means it cannot being in forged, forging mode.
