### ISSUE TITLE
External binary to update token/fiat prices in hermez node Postgres/L2 database

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#1095]
## Rationale

As Price Updater was removed from heznode and it's an independent project sometimes during the development or testing fases the token/fiat prices needs to be updated on demand. To avoid the developers or Q&A team needs to install the entire Price Updater service it would be good to have a separated CLI binary that connects to heznode instance, queries the token/fiat table, make a HTTP request to a Price Updater getting the price info and update the token/fiat table. 

It has to receive all connections info and Price Updater URL via command line (as flags).

A new repo must be created to this and the language used to this should be Golang.

**Comment by tclemos** [comment]
To solve this issue, I've created a repo with this tool: https://github.com/hermeznetwork/tool-update-token-prices

I've already tested it with my internal testnet node and everything looks fine.

@jeffprestes, @marioidival and @mfcastellani could you please test it with your internal testnet node and let me know if the documentation and the tool are working fine for you?

Thanks.

**Comment by tclemos** [comment]
Project updated to add the API key parameter required by the new version of the price updater service.

**Comment by jeffprestes** [comment]
@tclemos thanks! And as the binary is working fine, I ask you please to close this issue.
