### ISSUE TITLE
Change PR settings to delete branches automatically after merge

### ISSUE THREAD

**Issue by tclemos** [hermeznetwork/hermez-node#1096]
## Rationale

Sometimes we forget to delete branches that we will not use anymore and were created for a specific feature or bug fix.

Talking with the team during one of the releases, we thought it would be a good idea to improve on this in order to have a cleaner and simpler repository for everyone working on it.

## Implementation

The idea is to find a way to set the `delete branch` as the default behavior when a PR is merged.

**Comment by fooock** [comment]
Check [this](https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) from the Github docs, maybe it helps

**Comment by ARR552** [comment]
This issue can only be done by a repo admin @jeffprestes

**Comment by jeffprestes** [comment]
Done.
