### ISSUE TITLE
Add support to Atomic Transactions to the hermez-node

### ISSUE THREAD

**Issue by arnaucube** [hermeznetwork/hermez-node#116]
(check https://github.com/hermeznetwork/hermez-node/issues/116#issuecomment-815658680 )

**Comment by jeffprestes** [comment]
@arnaucube could you please provide more details? 
It not clear to me what is needed here. 
Thanks in advance.

**Comment by arnaucube** [comment]
Currently the hermez-node supports 'simple' transactions, to send tokens from
one account to another, which was the design defined for the launch of the
mainnet. But, the Hermez protocol supports also transactions that are linked to
other transactions, which is supported through the Rq parameters of the
transaction data structure.

This issue was created to have in mind that the Rq features should be
implemented at some point after the mainnet launch, but not as a concrete
specified task.  Now that mainnet has been launch, once the roadmap moment for
Rq features arrives, this should be converted to a Milestone, which englobes
multiple issues/tasks, as this feature will require to add code to different
parts of the hermez-node (txprocessor, zkinputs generation, txselector, api, db,
etc). Also, probably would be good to use the opportunity to change a bit the
structs of the L2Tx data type (and it's usage and storage in the DB), as
currently the Rq parameters are directly in the L2Tx struct, but probably a
better approach would be to have another struct for the Rq parameters and use
that struct in the L2Tx.

This should be consulted with @jbaylina in matter of specification and of
roadmap timming.

For more details about Rq parameters, this is the current spec:
https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=l2
(which could also be extended and detailed).

**Comment by jeffprestes** [comment]
Thanks. Now it's clear.
Also, I've changed the tittle to reflect how @jbaylina name this item internally.

**Comment by Pantani** [comment]
I am going to close this one because we already have all definitions
