### ISSUE TITLE
[style] package names

### ISSUE THREAD

**Issue by ed255** [hermeznetwork/hermez-node#118]
https://blog.golang.org/package-names
> Good package names are short and clear. They are lower case, with no under_scores or mixedCaps.
> When renaming an imported package, the local name should follow the same guidelines as package names (lower case, no under_scores or mixedCaps).

Currently we have `ethCommon` that uses mixed caps.
Check all package names and import renames to make sure the adhere to the convention.

**Comment by jeffprestes** [comment]
This is only an alias to an external dependency. I don't think it compromise our code quality.
