### ISSUE TITLE
Problems when txs/batches reference token without values

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#218]
DB store historic USD value of txs and fees. However if at the moment of inserting this data on the DB a given token have not a specified price or it's outdated, this leads to inaccurate information that is hard to reason about later on.

**Comment by arnaubennassar** [comment]
Before tackilng this issue it would be nice to have an important discussion that may affect future deep changes on the node:

How important is for the node to expose fiat values for the transactions / tokens? Should we delegate this responsibility to the clients?

**Comment by jeffprestes** [comment]
Closed as we are removing this functionality from hermez-node and putting it at an external service.
