### ISSUE TITLE
L2 timeout - maxNumBatch Update

### ISSUE THREAD

**Issue by ed255** [hermeznetwork/hermez-node#282]
- [ ] TxProcessor (ZKInputs)

Pending implementation in circuits and specs.

**Comment by ed255** [comment]
The L2Tx maxNumBatch field is the `maximum allowed batch number when the transaction can be processed`.  This has been implemented in the circuits, and defined in the specs: 
- https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=l2
- https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=transaction-fields 
- https://docs.hermez.io/#/developers/protocol/hermez-protocol/circuits/circuits?id=decode-tx

Currently the node only accepts l2txs where this field is disabled (it's 0).  This is done by forcing the verification of the signature check to force this value to be 0.  If a user sends a different value, the hermez-node implementation of the tx verification will fail and reject the tx at the API level.

Implementing support for this parameter requires changes in the `TxSelector`, `TxProcessor` and `L2DB`.

**Comment by arnaubennassar** [comment]
Closed in favor of #926
