### ISSUE TITLE
kvdb checkpoint consistency

### ISSUE THREAD

**Issue by ed255** [hermeznetwork/hermez-node#438]
I have observed consistency problems with the kvdb when starting and stopping the node several times.  This happens with graceful shutdowns (no crashes).

The observed behavior is that after a few restarts, the node is unable to start, throwing an error when opening the TxSelector statedb. The error is given by the pebble library, it complains that there are missing files in the pebble folder.

I'm not sure exactly why this error is happening, but I've checked the implementation of the checkpoint and I think it can lead to inconsistent states in the event of a crash.  This may not be related to the observed error stated before.  The issue I see is that when making a checkpoint the following happens:
1. Store the new batchNum in `current`
2. Make a checkpoint from `current` to `batchNum`.
If the process crashes between 1 and 2, or during 2, in the next start the KVDB will try to open `batchNum` which may not exists or be incomplete.

**Comment by jeffprestes** [comment]
Closing this as hermez-node's behaviour is exactly as mentioned in the previous comment. As we're developing methods to backup and resync easily and hermez-node has been stable in the last months there is nothing to change in hermez-node statedb package.
