### ISSUE TITLE
Update ProofServer client and README

### ISSUE THREAD

**Issue by ed255** [hermeznetwork/hermez-node#446]
The ProofServer client was implemented when the ProofServer had a timing issue and a long setup.  This means that:
1. Currently the test code has a sleep to avoid the timing issue
2. The testing instructions are long

The ProofServer has been updated to fix the timing issue and shorten the setup, but this is not yet implemented in hermez-node.

**Comment by ed255** [comment]
@laisolizq and @druiz0992 have information about this and can help addressing this issue.

**Comment by jeffprestes** [comment]
@druiz0992 is working on a tutorial how to setup a new proof server. 
I am waiting for new server environment to implement the instructions defined at the tutorial to create a new proof server and testing it as an external coordinator (in an external hermez IT environment too). 
After this, we're going to be able to test the proofserver performance and discard the mock proof server.

**Comment by druiz0992** [comment]
Here you can find the latest version of the tutorial https://github.com/hermeznetwork/docs/blob/feature/coordinator2/docs/developers/coordinator.md

Its still not in main, pending to have the multicoordinator feature completely validated

**Comment by jeffprestes** [comment]
Closing this as @druiz0992 already created a doc related to this in docs repo and also other modifications were applied at hermez-node to deal with proof server long processing
