### ISSUE TITLE
In test.Client, make `RollupForgeBatch` apply the tx at mine time and not in call time

### ISSUE THREAD

**Issue by ed255** [hermeznetwork/hermez-node#492]
Currently the `RollupForgeBatch` returns immediately if the tx fails, but this is not the right behaviour!
The right behaviour is that a call to `RollupForgeBatch` queues the txs (and possibly applies it to the forging block), but doesn't return any revert error.
Once the next block is mined, the tx will either be successfull or failed, and this can be queried by the receipt of the TxHash.

Also it would be very interesting to simulate account nonces and gasPrice.

**Comment by ed255** [comment]
This is an enhancement that would allow better testing of different conditions that coordinator can face that are currently not being unit tested.

**Comment by jeffprestes** [comment]
Closing it as this behaviour never happened in mainnet also GETH nodes in general simulate the call to Smart Contracts methods before to submit it to Ethereum's node transaction pool. So if it fails when submitting likely it is going to fail during mining process. This process saves user's time and very used by Ethereum projects such as Metamask.
