### ISSUE TITLE
Improve unit tests

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#624]
- [ ]  Split all tests we can run standalone (unit tests) from the tests we need to runs the database (flow/integration tests) with build flags;
- [ ]  Creates more mock interfaces for we can test the methods more independent and individually;

**Comment by jeffprestes** [comment]
Closing this issue in favor to open one more specifics to each package. A lot of items are not covered by unit test yet and breaking this issue in minor one would help to split the job among the team.

**Comment by Pantani** [comment]
The build flag for tests still necessary, and we don't need to break it into small tasks

**Comment by Pantani** [comment]
We need to create small unit tests with better mock and split the tests with database dependency by building flags. It's was not done
