### ISSUE TITLE
Improve prometheus metrics

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#628]
- [x] Create a metrics packages
- [x] Application Metrics (error/panic rates);
- [x] Database connections (Connectivity, Latency);
- [x] API requests (node API requests);
- [x] 3trd-party HTTP requests (prof server);
- [x] Host-Based Metrics (CPU, Memory, Disk space, Processes);

**Comment by arnaubennassar** [comment]
@Pantani I see that all the items on the list are marked as done, can you close this issue?
