### ISSUE TITLE
Consider generating OpenAPI spec using go-swagger

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#678]
@Pantani suggested to use this tool https://github.com/go-swagger/go-swagger to generate the Swagger / OpenAPI spec. This looks very interesting as it could simplify the maintenance of the documentation. This issue is opened with the purpose to discuss if we adopt this tool or not.

I'd like to have a list of PROS / CONS as well as implications with the existing code and tools we already use.
A few things that I think we should check before jumping into it:

- Does it actually work? It may seem even offending to ask it, but I've found many swagger related tools in the past that misbehave once the specification was complex enough
- How many "swagger related" do we want to have in our code? At some point I guess that it can be distracting to have lots of comment lines in the middle of files that are not API related
- Swagger uses a lot of references, it may be not practical to have the definitions of the objects spread across the repo, and probably IDE tools won't work using this
- What would happen if we split the `hermez-node` code into many repos due to a big refactor, would this still work?

I think this can actually be great but I would prefer to implement this for `v1` after we have thought deeply on the architecture of the node

**Comment by Pantani** [comment]
The go-swagger works well. We need to create some comments for the API handlers methods, like here:
https://github.com/trustwallet/blockatlas/blob/master/api/endpoint/transaction.go#L12-L22

and each new change, we must regenerate the swagger files:
https://github.com/trustwallet/blockatlas/blob/master/Makefile#L157-L158

and the files going to be autogenerated into the `docs` folder, like here:
https://github.com/trustwallet/blockatlas/tree/master/docs

It's easy to use and doesn't have too much code unless the generated files. It can be easier to maintain

**Comment by jeffprestes** [comment]
Closing it as we don't consider this change will bring value to the project right now. It might be reopen if somebody external would be interested in to implement it.
