### ISSUE TITLE
Avoid creating unnecesary accounts

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#680]
Scenario:

1. Alice sends a `createAccount` tx using the wallet (L1 tx)
2. Bob sends a `transferToEthAddr` to Alice (L2 tx)
3. Coordinator forjes the L2 tx, to do so creates an account on behalf of Alice
4. Coordinator forjes the L1 tx, which also creates an account for Alice

As a result Alice has two accounts, which probably is something she didn't want. And the coordinator had to create one extra account.

There are two strategies to mitigate this:

- [x] `txselector` avoid creating new accounts on behalf of users when there are pending L1 txs that will do that anyway
- `api` expose information that helps wallet avoiding the situation:
    - [x] Pending L1 that create accounts for a given Ethereum address
    - [x] Pending L2 that may create an account on behalf of the user: will be done by #548

**Comment by ed255** [comment]
I will add a tick to the first item in the checklist due to this PR being merged into develop: https://github.com/hermeznetwork/hermez-node/pull/688

**Comment by jeffprestes** [comment]
Should we close this in favor of #739 or vice-versa?

**Comment by arnaubennassar** [comment]
Closing this issue as all the items are covered, however this is not trivial from the point of view of a wallet, and I don't know how we should document this sort of thing
