### ISSUE TITLE
history for the FFAddr shows all CreateAccountDeposit and TransferToBJJ

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#687]
getting the transaction history for the `FFAddr` (`0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF`) is returning all `CreateAccountDeposit` and `TransferToBJJ`. Is this the right behavior?

https://api.testnet.hermez.io/v1/transactions-history?hezEthereumAddress=hez:0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF&order=ASC&limit=2049

Also, the explorer is showing only the first baby jubjub account 
https://explorer.testnet.hermez.io/user-account/hez:0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF
but we have other accounts for the `FFAddr` address:
https://api.testnet.hermez.io/v1/accounts?hezEthereumAddress=hez:0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF&order=ASC&limit=20

**Comment by Pantani** [comment]
by @arnaucube:

> Good catch! This could be due the `0xfff...fff` eth address is used to indicate when a L2 account with only BabyJubJub key is created (without having an ethaddr linked to that account), in these cases, the `tx.ToEthAddr = 0xfff...fff`. This is something that is part of the protocol, but probably the API could filter out the txs related to `0xff...fff`, as will be not txs generated by 'the owner' of the eth address `0xfff...fff` (if some of you have the private key of the eth address `0xfff...fff` just contact me, you would be rich on ethereum mainnet :money_with_wings: ).
I would say that ideally the API should not return the txs related to `0xfff...fff` or the BatchExplorer could show the txs related to `0xfff...fff` gotten from the API, as it's a useful way to get in the screen all the txs related to L2-only accounts (accounts with only BabyJubJub key of the user, without ethaddr (with ethaddr=0xfff...fff))

**Comment by arnaubennassar** [comment]
> but we have other accounts for the FFAddr address

As @arnaucube  mentioned `0xff...fff` is used to indicate `internal account`. So it's normal to have many accounts with such an Ethereum address

> the explorer is showing only the first baby jubjub account

Could you report this to the fellas working on the explorer: @mmilenkovic 

>  is returning all CreateAccountDeposit and TransferToBJJ

It's normal for `TransferToBJJ`, however for `CreateAccountDeposit` it doesn't make sense as this is a L1 tx so it's absolutley required for the account to be linked to an Ethereum address.

I've opened an issue to discuss if we return `null` instead of `0xfff...ff` in the API: https://github.com/hermeznetwork/hermez-node/issues/690

**Comment by Pantani** [comment]
hm, I found, this is a [CreateAccountBjj](https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=createaccountbjj), called from a [TransferToBjj](https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=transfertobjj). But the type was defined as `CreateAccountDeposit`, maybe we need change it to `CreateAccountBjj`.

**Comment by Pantani** [comment]
we can track the issue by this one: #690

The type change implementation from `CreateAccountDeposit`, to `CreateAccountBjj` must be made into the smart contract
