### ISSUE TITLE
Should API return null instead of 0xfff...ff

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#690]
`0xfff...ff` are used to indicate `internal accounts` however from the point of view of the API (which intends to simplify some of the details of the protocol) it may be interesting to return `null` instead

**Comment by Pantani** [comment]
I agree to return `null`, IHMO the pros:

- it's can be more clear for the end-user who don't know a lot about the protocol
- solves the UI problem related to show the `FFAddr`

and the cons:

- can be harder to debug
- maybe can break some UI integration

**Comment by jeffprestes** [comment]
I agree it can break the UI. What would be an alternative @Pantani ?

**Comment by jeffprestes** [comment]
Closing this after conversation with frontend team and we don't any reasons for changes.
