### ISSUE TITLE
better manage the test dependencies

### ISSUE THREAD

**Issue by Pantani** [hermeznetwork/hermez-node#693]
some test packages are consuming the node memory and are never used, like the [go-bip39](https://github.com/hermeznetwork/hermez-node/blob/master/go.sum#L646-L646), imported by the [HDWallet](https://github.com/hermeznetwork/hermez-node/blob/master/go.mod#L21-L21) into the [tests](https://github.com/hermeznetwork/hermez-node/blob/master/eth/main_test.go#L17-L17)

![Screen Shot 2021-03-31 at 21 22 03](https://user-images.githubusercontent.com/2406457/113227013-eff48b80-9267-11eb-9b56-6bc8ee8f5de7.png)
![Screen Shot 2021-03-31 at 21 27 08](https://user-images.githubusercontent.com/2406457/113227019-f1be4f00-9267-11eb-83ad-33dc2ee66b3c.png)

**Comment by jeffprestes** [comment]
Could this issue be incorporated at #624 issue? I think it is going to be better to concentrate the efforts in one issue.

**Comment by jeffprestes** [comment]
@stunndard as you're working on other unit test related tasks, could you please chat with @Pantani in order to get more details of this issue and improve this part of hermez-node?

**Comment by Pantani** [comment]
@stunndard some package is using this package for the bip39:
https://github.com/tyler-smith/go-bip39

This package uses the same big global variables, and it's is save in the memory, and we are not using it:
https://github.com/tyler-smith/go-bip39/blob/master/wordlists/english.go#L22-L23

We need to find a way to remove it. you can debug using the memory profiling:
https://golang.org/pkg/runtime/pprof/

**Comment by stunndard** [comment]
@Pantani do you have a better idea than forking the hdwallet package?

**Comment by stunndard** [comment]
IMO we shouldn't do anything about this problem. The mentioned amount of wasted memory is too small (0.5 MB), it only affects the test environment and does not seem to be easy to fix without changes in 3rd party packages.

**Comment by Pantani** [comment]
> IMO we shouldn't do anything about this problem. The mentioned amount of wasted memory is too small (0.5 MB), it only affects the test environment and does not seem to be easy to fix without changes in 3rd party packages.

@stunndard, I agree, it's too small, but it's 1.2% of all node memory. It takes more memory than a simple method. And it's forever saved in the node runtime. I got this print profiling the similar binaries we are using in prod. But we can forget about it because it is too short. What do you think?

**Comment by stunndard** [comment]
go-bip39 package is used by go-ethereum package:
https://github.com/ethereum/go-ethereum/blob/e7872729012a4871397307b12cc3f4772ffcbec6/go.mod#L61

@Pantani @jeffprestes I'm going to close this issue if no one objects
