### ISSUE TITLE
Better filters before inserting txs to the pool

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#694]
## Check from (origin)

- Idx exists and match tokenId
- nonce > currentNonce

### Transfer

- Idx exists and match token

### Transfer to Eth addr

- Eth addr exists and has idx with token or authorization

### Transfer to BJJ

- BJJ exists and has idx with token or authorization

**Comment by jeffprestes** [comment]
@Pantani could you please write here the other verification we need check before to accept the transaction?

**Comment by Pantani** [comment]
We need to improve the verification here. If the IDX is set and valid, we must validate the toBjj and toHezAddr are empty.

https://github.com/hermeznetwork/hermez-node/blob/8ee9d05ddcdb37e8b66fa55c1b342c802ce7d792/common/pooll2tx.go#L94-L94
