### ISSUE TITLE
Non forjable old TXs do not get deleted from txPool after TTL

### ISSUE THREAD

**Issue by jbaylina** [hermeznetwork/hermez-node#701]
TTL only applies if the pool is full. It should be appliead always.

**Comment by jeffprestes** [comment]
What protocol says if a user post his tx but the coordinator doesn't get it from the pool and forge it into a batch?
Will the user has his tx lost?

**Comment by Pantani** [comment]
@jbaylina, we have a TTL checking each new batch and block. If any transaction reaches the maximum duration time in the pool, we invalidate and remove it from the pull. Maybe the TTL time from the config file is too long.

https://github.com/hermeznetwork/hermez-node/blob/0c08ec7395dc200e652cfcad19fe8f06036686d0/cli/node/cfg.buidler.toml#L103

**Comment by Pantani** [comment]
With this PR, we can skip adding most of the invalid transactions in the pool:

https://github.com/hermeznetwork/hermez-node/pull/708

**Comment by ed255** [comment]
> @jbaylina, we have a TTL checking each new batch and block. If any transaction reaches the maximum duration time in the pool, we invalidate and remove it from the pull. Maybe the TTL time from the config file is too long.
> 
> https://github.com/hermeznetwork/hermez-node/blob/0c08ec7395dc200e652cfcad19fe8f06036686d0/cli/node/cfg.buidler.toml#L103

@Pantani 
The method that cleans txs is this one: https://github.com/hermeznetwork/hermez-node/blob/e1b2ff82b41bbacba161296caea75cfc255859bf/db/l2db/l2db.go#L369
Which uses this query:
```
`DELETE FROM tx_pool WHERE (
			batch_num < currentBatchNum-l2db.safetyPeriod AND (state = common.PoolL2TxStateForged OR state = common.PoolL2TxStateInvalid)
		) OR (
			(SELECT count(*) FROM tx_pool WHERE state = common.PoolL2TxStatePending) > l2db.maxTxs 
			AND timestamp < time.Unix(now-int64(l2db.ttl.Seconds()), 0) AND state = common.PoolL2TxStatePending
		);`
```
I've replaced the `$X` by the arguments for better readability.  Notice that transactions that exceed the TTL are only deleted when the max number of pending txs is reached.  I think that the check that pending txs is over maxTxs should be skipped, and delete pending txs which exceeds TTL unconditionally.

**Comment by jeffprestes** [comment]
> With this PR, we can skip adding most of the invalid transactions in the pool: #708

I think here you avoid that new invalid transactions comes in into transaction pool, am I correct?
