### ISSUE TITLE
Improve config file validation

### ISSUE THREAD

**Issue by OBrezhniev** [hermeznetwork/hermez-node#710]
## Rationale
Right now validation of values is done by custom code in the node initialization code and in different other places around the code and there are inconsistencies, in some cases it throws errors:
https://github.com/hermeznetwork/hermez-node/blob/e38413db4463588a69ea6de8c9d71ce702b0797a/node/node.go#L226-L230

in others - just logs a message:
https://github.com/hermeznetwork/hermez-node/blob/e38413db4463588a69ea6de8c9d71ce702b0797a/priceupdater/priceupdater.go#L176-L179

Also it would be good to have default values for config params (where it makes sense) and make them optional to keep the file small and clean.

This would also improve user experience by requiring less changes to config file from the user on node updates, because right now on each addition/removal/name change of config parameter in the code the user is required to update the config file.

## Implementation
Validation rules can be added uniformly in config structure definition and validated on node start. 
See https://github.com/go-playground/validator (that is already used to check "required" fields) for available rules.
Only more complicated checks would require custom code, like for PriceUpdater.

**Comment by jeffprestes** [comment]
Thanks @OBrezhniev . In order to help who's going to take this task, could you please share in example of the situation you mentioned?

**Comment by OBrezhniev** [comment]
Sure, updated the issue description, @jeffprestes
