### ISSUE TITLE
Add default values to config params

### ISSUE THREAD

**Issue by OBrezhniev** [hermeznetwork/hermez-node#711]
It would be good to have default values for config params (where it makes sense) and make them optional to keep the file small and clean. 

This would also improve user experience by requiring less changes to config file from the user on node updates, because right now on each addition/removal/name change of config parameter in the code the user is required to update the config file.

**Comment by OBrezhniev** [comment]
merged with #710

**Comment by jeffprestes** [comment]
It would great during hermez node start up it tries to get parameters from:

- system variables: os.GetEnv;
- toml config file;
- if does not find any above hermez-node should use default values

This would allow users to only define sets they wants to change and use the standard value most of time.
