### ISSUE TITLE
Error message when an Idx does not exist 

### ISSUE THREAD

**Issue by laisolizq** [hermeznetwork/hermez-node#722]
## Rationale

When an invalid L2 transaction is sent, the node returns errors with the reason why it is invalid.
When an IDx does not exist, it returns an error like: `Error getting from account: sql: no rows in result set` because it cannot be found in the DB.
Would it be possible to also add an error message for this case?
For example: `Error: IDx not found in state-tree`

**Comment by Pantani** [comment]
@laisolizq we have plans to create a better error mapping:

https://github.com/hermeznetwork/hermez-node/issues/627
