### ISSUE TITLE
Provide early feedback when a transaction is not processed 

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/hermez-node#726]
## Rationale

 Currently, when a transactions is discarded and not processed in the current batch, some feedback is added when querying the TxId in the transactions pool. However, this feedback is provided only after one batch is forged. If there is no batch being forged, time to get a response is undefined, and user will not know how to fix it.

This issue is specially acute now that we are trying to ramp up the volume or transactions and user experience of early adopters is critical.

**Comment by jeffprestes** [comment]
Example of the situation where a transaction has waited 30 minutes, and until someone has sent another and has forged it, I have not seen the reason
https://api.testnet.hermez.io/v1/transactions-pool/0x02da9620acd56bc44e8d8a5cb080fd90ab2c8e254d008272dc36fd859656426cac

**Comment by Pantani** [comment]
This PR can help to solve most of these failure cases: https://github.com/hermeznetwork/hermez-node/pull/708

**Comment by jeffprestes** [comment]
For sure that PR is going to avoid invalid tx to be included at the pool but I guess the issue is not related to filter and avoid them but make any invalid tx (maybe other situations can come up) be visible before a batch being forged.

**Comment by jeffprestes** [comment]
@Mikelle maybe this PR did by you can address this situation. Could you please confirm it? 
https://github.com/hermeznetwork/hermez-node/pull/689

**Comment by Mikelle** [comment]
@jeffprestes @druiz0992 Yes, it seems, that my request PR will fix this because we can request transactions from the transaction pool

**Comment by jeffprestes** [comment]
The PR related is: https://github.com/hermeznetwork/hermez-node/pull/689

**Comment by druiz0992** [comment]
I am not sure issue is fixed but PR #689. I am testing in internal testnet with node version `v1.2.0-rc1`.

I request a transfer from account A to account B of amount exceeding account A's balance. The transaction is pending on the `transactions-pool` with this message `"info": "Tx not selected due impossibility to be forged with the current state"`. This message is displayed until the next batch is forged. At this point, the message changes to `"info": "Tx not selected due to not enough Balance at the sender. Current sender account Balance: 99800849901981366, Amount+Fee: 1000410593952760602"`.

My problems with current flow are:
- Even though initial message ``"info": "Tx not selected due impossibility to be forged with the current state"` is displayed quite soon, the text doesn't really mean anything to an end user. We plan to show this message in the wallet to provide feedback on the transaction status, so it would be nice that the message was meaningful to end user.
-Second message is good, but it is only displayed after a batch has been forged and this may be too long in the future. In the scenario where few transactions are being sent,  a user could wait for hours to get the reason why his transaction wasn't processed.

**Comment by druiz0992** [comment]
A releated scanario. A user requests a transfer and for some reason, the nonce computed by `hermezjs` is incorrect. The transaction is flagged as `invalid` and no feedback is given in the info field
![Screenshot from 2021-04-28 12-30-46](https://user-images.githubusercontent.com/46495002/116389977-e25a0380-a81d-11eb-8749-dfe6e1beb715.png)

**Comment by jeffprestes** [comment]
Could you please share the response the user is receiving?

**Comment by druiz0992** [comment]
I don't follow. The json above is the response the user is receiving when querying the status of the transaction in the transaction pool. The response received when submitting the transaction if that is what you want is not available.

**Comment by jeffprestes** [comment]
The situation explained by @druiz0992 is: 
Here https://github.com/hermeznetwork/hermez-node/blob/97f462c4a58280cbb59b824f5c8979dfa4277499/txselector/txselector.go#L774 the tx is evaluated and the sender's account balance is checked. It is put aside of tx will be processed. But the user has no good information of the issue. Also, this check is being doing in a wrong moment because another transaction can be added to the pool depositing funds to the account.
Hence, two changes are required. Made splitL2ForgableAndNonForgable method return a proper feedback to the tx for nonce error and remove the balance check of this method.

**Comment by Pantani** [comment]
The balance check is wrong, but maybe by removing it, we will delay more time to receive the tx information, maybe from the circuits. My IHMO is to create a better check before adding it into the pool and removing the maximum of complexity from the TxProcessor. My suggestion is to have a copy of the state DB with future changes already applied by transactions from the pool. The API can check each new valid transaction before applying to the pool and provide early feedback. What do you think?

**Comment by jeffprestes** [comment]
As per our conversation @Pantani , we agree that the @Mikelle fits better the business needs in the actual moment. 
For sure, in v2 (atomic tx) improvements a best way to handle this will be implemented.
So, based on this, could you please review the #787 PR?
