### ISSUE TITLE
Use EtherScan gas estimations

### ISSUE THREAD

**Issue by ARR552** [hermeznetwork/hermez-node#729]
## Summary
Use EtherScan gas estimations rather than ethereum node estimations because etherScan provide more accurate estimations than an ethereum node that can  provide outdated estimations under some circunstances

### Expected Behavior
Gas estimations should be more accurate when gas is growing quickly to prevent ethereum tx (containing batches) from failing

**Comment by Pantani** [comment]
Somethings to be aware of. We should worry about the API rate limit, which is too short, and also, they don't give a warranty about this API uptime. Also, we need to mention them in some parts of the project to use it.

https://etherscan.io/apis
```
The Etherscan Ethereum Developer APIs are provided as a community service and without warranty, so please use what you need and no more. We support both GET/POST requests and there is a rate limit of 5 calls per sec/IP.

1. To use the API service please create a FREE Api-Key Token from within the ClientPortal->MyApiKey area which you can then use with all your api requests.

2. Kindly refer API Key Rate Limit & Errors for expected returns. Please contact us if you would like to upgrade your API Plan.

3. Source attribution via a link back or mention that your app is "Powered by Etherscan.io APIs" is required except for personal/private usage.
```
