### ISSUE TITLE
Avoid to create unnecessary accounts

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#739]
## Summary of Bug

Duplicating accounts with the same BJJ address with same tokenID

### Expected Behavior

When /transaction-pool receives a new tx where the recipient (to field) is a BJJ address, it should perform a query in account table in database for this BJJ address before to return an error and asking to the user to register it at /account-creation-authorization

In account table it's possible to an account to have a BJJ and ETH address set and the tx sender could be allowed to send L2 tx to any account using either BJJ or ETH address without creates a new account.

### Steps to Reproduce

To check this please verify the hez:0x7CaEFD0214dCd8305A7991eB8E016d3a76822189 in Goerli/Internaltestnet

**Comment by Pantani** [comment]
`TransferToBjj` don't have this verification, only for `TransferToEth` and `Transfer`

https://docs.hermez.io/#/developers/protocol/hermez-protocol/protocol?id=account-types

**Comment by Pantani** [comment]
If we merge this implementation, we can break some exchanges integrations

**Comment by jeffprestes** [comment]
After meeting with Jordi, Carlos and Bennassar we checked the user can send tokens to a BJJ that is not already created but internally the before the hermez-node create a new account (and/or leaf in Merkle Tree) it needs to check if the account already exists and reuse it. The API must accept the transaction and handle this internally.

**Comment by arnaubennassar** [comment]
Closed in favor of #680
