### ISSUE TITLE
make build will fail if packr2 is not installed

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#742]
## Summary of Bug

`make build` will fail if `packr2` is not properly installed, the Makefile tries to install it, but it may fail depending on the `GOPATH` configuration of each user. 

### Expected Behavior

`make build` works in a clean environment (without having `packr2` already installed).

### Steps to Reproduce

1. Make sure  `packr2` is not installed on your machine
2. Run `make build`, it should fail

**Comment by jeffprestes** [comment]
To appropriate test this situation you need to try to build the binary in a new machine.
Based on my tests it lacks of GOPATH and/or PATH settings. When you run go get -u ...packer2 it puts the binary at GOPATH/bin but as it's not at system PATH it is not found by make task and return an error.

**Comment by Pantani** [comment]
we could do the Makefile check if the packr2 were installed and install if needs

**Comment by jeffprestes** [comment]
Actually, Makefile installs packer2 in this line: 
```bash
@cd /tmp && go get -u github.com/gobuffalo/packr/v2/packr2 && cd -
``` 
but Go compiles and put the binary at $GOPATH/bin . However, the new machine does not have set $GOPATH/bin in their PATH so the next line 
```bash
@cd $(GOBASE)/db && packr2 && cd -
```
fails because the system of the new machine does not find the packr2 binary

**Comment by Pantani** [comment]
@arnaubennassar I created a better Makefile verification:
https://github.com/hermeznetwork/hermez-node/pull/748
