### ISSUE TITLE
Do statedb synchronization profiling/optimization

### ISSUE THREAD

**Issue by stunndard** [hermeznetwork/hermez-node#744]
## Rationale

Sync performance is very important for both Synchronizator and Coordinador modes.
Need to be able to measure KVDB performance, detect and fix bottlenecks.

## Implementation

 - `go tool pprof` could be used for profiling;
 - benchmark mode could be added (e.g. import first 5000 batches into empty StateDB);
 - maybe add some StateDB metrics to the Prometheus exporter (`/debug/metrics`).

**Comment by stunndard** [comment]
Results of a small profiling session, it looks like `NewPebbleStorage` is the most expensive call here
![image](https://user-images.githubusercontent.com/9940084/115687570-f9eb4500-a362-11eb-95e0-ba8402122584.png)

**Comment by jeffprestes** [comment]
@marioidival @arnaubennassar @mfcastellani

**Comment by jeffprestes** [comment]
@mfcastellani as we have talked this issue might be a good item related to Ethereum for refactoring.

**Comment by tclemos** [comment]
We are going to handle this in the new synchronizer implementation and more details can be found in issue #740
