### ISSUE TITLE
API style: protocol vs extra safety checks

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#751]
Currently the API performs some sanity checks, that may invalidate transactions even were they are valid as per the protocol.
Examples of such conditions are:

- TxID: TxID doesn't even exist in terms of protocol, it's an add-on of the node, and yet a transactions can be rejected just because an invalid TxID
- ToEthAddr and ToBJJ: those fields are ignored when ToIdx > 255, however the API will check that this values are empty and reject otherwise

This situation is not wrong, but it would be nice to take a meditated decision towards either strictly follow the protocol or keep it as it is (perform extra sanity checks, that may invalidate things that are valid in terms of protocol)

**Comment by jeffprestes** [comment]
The hermez-node is an extension of the protocol. Some verifications and sanity check must be implemented by it.

**Comment by jeffprestes** [comment]
@Mikelle has refactored the API validations and these checks were included.
