### ISSUE TITLE
API return an invalid pendingItems when calling GET v1/transactions-pool

### ISSUE THREAD

**Issue by invocamanman** [hermeznetwork/hermez-node#758]
## Summary of Bug

When perform the api call GET `https://api.internaltestnet.hermez.io/v1/transactions-pool` (internal testnet example, also happens in local), it returns correctly the transactions, but the `"pendingItems":18446744073709551596` is always an enormous number ( also happens in local with no transactions) 

### Expected Behavior

`pendingItems` should be `total items - the items fetched`

### Steps to Reproduce

call GET `https://api.internaltestnet.hermez.io/v1/transactions-pool`

### System information
- OS: `Linux`

### Additional Information:

**Comment by Mikelle** [comment]
@invocamanman This thing already fixed and in the develop branch. https://github.com/hermeznetwork/hermez-node/issues/750
