### ISSUE TITLE
Lint test in Makefile is failing

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#760]
## Summary of Bug

Lint test in Makefile is not working . It says it is missing a parameter

### Expected Behavior

Tests run

### Steps to Reproduce

```bash
make test
```

### System information

- Heznode version: develop branch - tag v1.2.0-rc1
- OS: `OSX`

### Additional Information:

The actual logs are:

```bash
hermez-node (develop)$ make test
  >  Running go vet
  >  Running Golang CI Lint
make: golangci-lint: No such file or directory
make: *** [gocilint] Error 1
```

**Comment by stunndard** [comment]
Already fixed in my local branch, will upload on Monday.
