### ISSUE TITLE
Valid transaction is mark as invalid

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/hermez-node#763]
## Summary of Bug
Valid transaction marked as invalid

### Expected Behavior
Accept valid transaction in `hermez-node`

### System information
- Node version: `v1.2.0-rc1`
- OS: `Linux`

### Additional Information:
Account state provided by endpoint (`GET https://api.internaltestnet.hermez.io/v1/accounts/hez:HEZ:21961`) was giving nonce information as 1031.
A valid tx, with nonce 1031, was sent to the `tx-pool` via the endpoint `POST https://api.testnet.hermez.io/v1/transactions-pool` and `tx-selector` mark that tx as invalid with the following message: "Nonce is smaller than account nonce"
This information has been extracted from endpoint: `GET https://api.internaltestnet.hermez.io/v1/transactions-pool?hezEthereumAddress=hez%0xD8Af0C5c6dEE7dCe32E59577675C026e1aDe4De5`

I attach a snapshot of the JSON result in the `tx-pool`:
```
{
"amount": "1000000000000000000",
"fee": 118,
"fromAccountIndex": "hez:HEZ:21961",
"fromBJJ": "hez:CqRL3r5Uz5G2wbwJWeQVE3W-7MlUkl9Rvolk77NWjZsz",
"fromHezEthereumAddress": "hez:0xD8Af0C5c6dEE7dCe32E59577675C026e1aDe4De5",
"id": "0x02c02639ee6130323ed12c4c1a5380adeffcc8c99e5c73413659b6eeda77cf9685",
"info": "Nonce is smaller than account nonce",
"itemId": 1671,
"nonce": 1031,
"requestAmount": null,
"requestFee": null,
"requestFromAccountIndex": null,
"requestNonce": null,
"requestToAccountIndex": null,
"requestToBJJ": null,
"requestToHezEthereumAddress": null,
"requestTokenId": null,
"signature": "8a92651c34d22e8ae74661cbf4cb38f38c0d87b22c636916d03ba490a80c7f9c79391801c24fd97fa2dedfabcb3a6dd82c40b51a0e531eabf3a89de83f414d02",
"state": "invl",
"timestamp": "2021-04-29T13:52:42.328138Z",
"toAccountIndex": null,
"toBJJ": null,
"toHezEthereumAddress": "hez:0x8f94Da4D8142b44299Db1F1BdEE4113a4092e46c",
"token": {
"USD": 6.7612,
"decimals": 18,
"ethereumAddress": "0x55a1db90a5753e6ff50fd018d7e648d58a081486",
"ethereumBlockNum": 4417287,
"fiatUpdate": "2021-04-27T10:25:18.458964Z",
"id": 1,
"itemId": 2,
"name": "Hermez Network Token",
"symbol": "HEZ"
},
"type": "TransferToEthAddr"
}
```

**Comment by jeffprestes** [comment]
The nonce verification for L2 transactions is made here: https://github.com/hermeznetwork/hermez-node/blob/develop/txselector/txselector.go#L770 
Maybe a good starting point for verification would be verify if the state is being rebuilt after synchronisation and it lost the proper nonce number.

**Comment by arnaucube** [comment]
The `txselector` could not mark the tx as invalid with this info message. Seems that the `info` message that appears is not set by the `txselector`, but by the tx purger from `l2db` (called from the coordinator) https://github.com/hermeznetwork/hermez-node/blob/develop/db/l2db/l2db.go#L322

The `txselector` checks the nonces, but the message in the `info` parameter of the tx would be different: https://github.com/hermeznetwork/hermez-node/blob/develop/txselector/txselector.go#L382

**Comment by arnaubennassar** [comment]
After digging a bit further, it looks like that the pipeline of forging a batch could lead to inconsistencies in the pool It goes a little bit like this:

1. Let's say we have more than one transaction from the same account and same nonce
2. Node starts forging a batch, selects one of the mentioned transactions and mark the others as invalid
3. The forging process fails for whatever reason (for instance, the proof server is not available)
4. If the changes made in the pool are not reverted, some valid transactions marked as invalid will be left in the pool
