### ISSUE TITLE
Release changelog doesn't include all the needed commits

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#772]
## Summary of Bug

The changelog message that is generated automaticaly for releases doesn't include all the expected commits

### Expected Behavior

Situation: `v1.2.0-rc1` adds commits 1, 2 and 3. `v1.2.0-rc2` includes commits 4, 5 and 6
What's happening as it is: changelog for `v1.2.0-rc2` includes commits 4, 5 and 6
What should happen: changelog for `v1.2.0-rc2` includes commits 1, 2, 3, 4, 5 and 6

### Steps to Reproduce

Since it's a bad idea to have "fake releases" to debug this, the ideal way to reproduce would be to:

1. Fork the repo
2. Create some branches on top of develop, add commits and merge them to develop
3. Create a tag in develop branch
4. Repeat step 2 and 3
5. Go to the release page of the forked repo and check which commits are included in each release changelog message

### Additional Information:

We're using goreleaser/goreleaser-action@v2 action to generate the message (among other release related stuff)

**Comment by jeffprestes** [comment]
@arnaubennassar , do you think this is something we can address changing goreleaser config file? Or is this a lack of goreleaser functionality?

**Comment by arnaubennassar** [comment]
TBH I believe this it has the right behavior. For example

- `v3.0.0-rc2` doesn't include the commits from `v3.0.0-rc1`
- `v3.0.0` includes the commits of `v3.0.0-rc1`, `v3.0.0-rc2`, ...
- `v3.0.1` doesn't include commits from `v3.0.0`

In other words the included commits come from the diff of the greatest segment modified. i believe this is right and we can close this issue
