### ISSUE TITLE
Transaction pool shared among Coordinators

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#777]
## Rationale

Today when a user needs to send a transaction she needs to know which coordinator is the forger in that time. Also, to know a transaction status she needs to pull information from a specific coordinator. Hence, tracks transaction status meanwhile they are not forged is complex and often brings confused information to the users.

## Implementation

Using gRPC, DRPC and/or LibP2P exchange information about transaction pool status among the coordinators.

**Comment by arnaubennassar** [comment]
Would love to have something like this implemented, and here a few extra motivations to do so:

- The protocol has a death line that allows anyone to forge if the current coordinator doesn't forge any batch after the specified blocks. However this (cool) feature is quite useless if all the transactions are sent only to the expected coordinators. If all the coordinators would receive all the transactions, the network could gracefully forge batches if there is some lazy coordinator.
- Not only for transactions, but also for authorizations, which is even harder to reason about as users are forced to send the authorizations to the next forgers, but their authorizations may be used at any point in time (compared with transactions that are supposed to be short term).

**Comment by arnaubennassar** [comment]
Another cool feature that could be enabled if we have a p2p communication mechanism among the coordinators, is the ability to synchronize data that is not available on Ethereum. In particular we could know if a transaction request another one, by doing this explorers and similar front ends, could show to users interesting information.

More info on this particular example and why it cannot be achieved by just synchronizing data from Ethereum #911

**Comment by arnaubennassar** [comment]
Closing as this issue is to big, instead I will creat a bunch of issues under the label https://github.com/hermeznetwork/hermez-node/labels/coord-net
