### ISSUE TITLE
Fix package names in eth/contract 

### ISSUE THREAD

**Issue by jeffprestes** [hermeznetwork/hermez-node#779]
Today the package names of Smart Contract wrappers under /eth/contracts seems are not following Go standards.

E.g.: at /eth/contracts/auction/HermezAuctionProtocol.go the package statement says "package HermezAuctionProtocol" and it would be "package auction" 

Because nowadays to use it we would need code the following statement, for instance: 
```go
import (
	HermezAuctionProtocol "github.com/hermeznetwork/hermez-node/eth/contracts/auction"
)

type HermezClient struct {
	AuctionClient *HermezAuctionProtocol.HermezAuctionProtocol
}
```

**Comment by Pantani** [comment]
There is another issue related to it. Who gets this one gets also fix this another one too:

https://github.com/hermeznetwork/hermez-node/issues/119
