### ISSUE TITLE
Implement an "evil coordinator" for testing purposes

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#797]
## Rationale

The protocol allows some stuff that we may not cover in the node for different reasons. Since this is a decentralized open source network anyone could deploy a node that behaves in a different way from the implementation found in this repo. If such thing happens we may have some vulnerabilities that are not considered right now, specially in the synchronization process.

The idea would be to have a minimalist implementation of a node that tries to forge transactions that otherwise wouldn't make it to the blockchain as the implementation in this repo won't forge them.

**Comment by jeffprestes** [comment]
Closing this as it's related more with protocol level than hermez-node specifically.
