### ISSUE TITLE
Remove TODOs

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#805]
## Rationale

It's hard to track the status of TODOs as it's very easy to forget about them. Instead wwe should rely on GitHub issues.

Search for all the `// TODO` in the code, and:
a) open an issue if it's an actual "TODO"
b) remove it, if it's not longer relevant

Also, it would be nice to add a linter that doesn't allow for more TODOs in the code once they're cleaned

**Comment by jeffprestes** [comment]
Closing it as it was done at v1.7.0-rc1
