### ISSUE TITLE
Rethink swagger documentation deployment

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#809]
## Rationale

The current deployment strategy has a few problems:
- The mock server is broken due to the service that we're using limitations (more info at #663), we decided to point to a deployed server as a workaround
- Right now the documentation is based on the latest changes on master, while this should work fine for production (mainnet), it's problematic for people testing or using non released changes (release candidates and similar) which may be deployed on testnets

## Implementation

I foresee two different approaches:
a) Use swagger versioning, this will probably mean to have separated swagger files for different versions. Then figure out how can we chose the version from the UI
b) Serve the documentation from the deployed `hermez-node`s making sure that the served documentation is consistent with whatever is deployed

IMO option `a)` is cleaner and doesn't force us to mess with production servers, but on the other hand maintaining the code this way can be ugly and we may end up having lot's of swagger files

**Comment by jeffprestes** [comment]
I would suggest to: as swagger file is part of herneznode code base I believe hermeznode could have an endpoint called /apidoc and present the api documentation based on swagger file is following the hermeznode.
This way when some user will consumes the hermeznode API the user will be aware which endpoints are available in that particular hermeznode version deployed into the server.

**Comment by arnaubennassar** [comment]
I agree with most of your points @jeffprestes, some considerations:
- We use a Docker container that take cares for transforming the swagger file into a web page and serving it, to do what you suggest, we need to figure out how to transform the swagger file into a static HTML, and then include it as part of the binary
- Not very fan of the idea of each node serving the documentation, although I don't like the word it feels better to have a `centralized` source of documentation

**Comment by arnaubennassar** [comment]
After talking with @jeffprestes , he suggested the idea of serving the swagger file from the `hermez-node`, and maintain the documentation server that will load the spec from there

**Comment by jeffprestes** [comment]
After couple months we realized that hermez-node api does not change a lot and the swagger file update is not frequent. Also, it has been served the user very well so we can keep it as a separated project.
