### ISSUE TITLE
Release postman collection and swagger file

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#811]
## Rationale

Many developers use swagger and postman as part of integration tooling. It would be very nice to include in the release:
- [ ] Postman collection file
- [ ] Swagger file

## Implementation

Use GitHub actions to make it automatic, the swagger file is straight forward as we already have it, but we need to figure out how to generate the Postman one. Note that Postman accepts swagger files as well.

**Comment by jeffprestes** [comment]
This task was already performed by @arnaubennassar and it has been included at release notes in some hermez nodes versions.
