### ISSUE TITLE
Include txHash of the L1 operation in L1Info of the Exit and Deposit transactions types in /transactions-history

### ISSUE THREAD

**Issue by rauljareno** [hermeznetwork/hermez-node#831]
## Rationale

Exit and Deposit transactions types in /transactions-history are not showing the txHash of the L1 operation or the fees in 'L1Info' object. It would be needed for showing the user in the native mobile app the L1 fee costs and substract them from the Ethereum Wallet balance

## Implementation

Add in L1Info a fee field like we are receiving already in the L2Info for the Hermez fees, and also include in L1Info a txHash field with the ethereum tx hash of the withdraw

Current Example of a Deposit:

     "L1Info": {
        "amountSuccess": true,
        "depositAmount": "3000000000000000000",
        "depositAmountSuccess": true,
        "ethereumBlockNum": 8643329,
        "historicDepositAmountUSD": 13.002,
        "toForgeL1TransactionsNum": 3018,
        "userOrigin": true
      },
      "L1orL2": "L1",
      "L2Info": null,
      ...

Current Example of a Exit:

      "L1Info": null,
      "L1orL2": "L2",
      "L2Info": {
        "fee": 62,
        "historicFeeUSD": 0.50039942514,
        "nonce": 18
      },
      ...

**Comment by arnaubennassar** [comment]
Note that L1 and L2 fees are very different concepts:
- L1: this is the regular Ethereum fee aka the gas, and it's always paid in Ether to the miners in proportion to the computational cost of processing the tx
- L2: this is a fee paid to the Hermez coordinators to include the tx in a batch. It's paid in the same token as the transfer

As of now we are not synchronizing the transaction that creates the L1tx (smart contract interaction). In other words right now we don't know the fee or the tx hash for the L1s. However, users need an Ethereum wallet to perform such transactions and this wallet should know this info, maybe you can get this from there?

**Comment by arnaubennassar** [comment]
After further analysis we've decided to add the Tx hash that originates the L1 tx. To achieve this we have to:
- [ ] Capture the tx hash in the `synchronizer`
- [ ] Store it in the `historydb` (this will require a new migration)
- [ ] Add this info in the json response of the `api`
