### ISSUE TITLE
consider using oapi-codegen

### ISSUE THREAD

**Issue by tclemos** [hermeznetwork/hermez-node#838]
## Rationale

`oapi-codegen` is a tool to generate code based on an OpenAPI 3.0 specification, see more here: https://github.com/deepmap/oapi-codegen

This tool allows the team to focus on designing the API interface before starting developing it, allowing multiple teams to have the interface available as soon as possible. It allows us to generate all the boring code needed to expose or consume an HTTP API automatically. 

It forces the API documentation to be in sync with what is delivered because the code is generated from the documentation.

It forces the team to start an API development by its interface instead of the implementation, so it helps thinking about breaking changes and retro-compatibility from the beginning of the task.

Since the OpenAPI is code, it is easy to be maintained by the project contributors inside of the project repository that will expose the APIs, allowing other teams to easily find it and take advantage of that, also, having it available in the repository allows us to integrate any other tools like ReDoc(https://github.com/Redocly/redoc) to publish a friendly UI based on the same document or maybe provide an automatically generated HTTP client in a specific programming language. 

Having the documentation in the same repository as the project also helps to find all the things in one place, making it easy to be shared or found.

It is possible to add the generation commands during the CI process to avoid someone forgetting to generate it locally, allowing us to identify automatically part in the documentation that does not reflect the current implementation.

## Implementation

First of all, we need to understand if it's possible to replace our current implementation with this new one.
The library recommends the usage of Echo as the web framework, we need to check if it fits all the project needs.
The introduction of this feature can be incremental, but it can require some infrastructure help to allow both codes to live together while the migration is not finished, this strategy will require the service to provide 2 web servers at the same time.

**Comment by arnaubennassar** [comment]
@tclemos could you have a look into #678 and merge this two issues into a single one as they are very similar?

**Comment by jeffprestes** [comment]
It's a nice idea but how hermez-node is implemented it would requires a huge refactor and the gains with this does not justify the total amount of effort.
