### ISSUE TITLE
`MaxGasPrice` default configuration parameter

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/hermez-node#847]
## Summary of Bug

Rather than a bug, this is a suggestion :)
There is a parameter in `hermez-node`, [`MaxGasPrice`](https://github.com/hermeznetwork/hermez-node/blob/develop/cmd/heznode/cfg.buidler.toml#L125) which is set by default to 5 GWei. At the same time, there is a hardcoded value in the code which sets a minimum gas price of 5 GWei, https://github.com/hermeznetwork/hermez-node/blob/develop/coordinator/txmanager.go#L139
Given that minimum gas price hardcoded is incremented a percentage given the [GasPriceIncPerc](https://github.com/hermeznetwork/hermez-node/blob/develop/cmd/heznode/cfg.buidler.toml#L126), default parameters lead to an error when tries to send `forgeBatch` transactions to ethereum network if the chain used has a low gas price per default when asking to the Ethereum node.

My suggestion is to increase the `MaxGasPrice` default parameter to a value that don't trigger this error. It should be `X > 5.5 GWei` ( It could be 100 GWei, just an example )

### System information

- Node version: `v*.*.*`
- OS: `Linux/OSX`

**Comment by jeffprestes** [comment]
Closes in favor of #846
