### ISSUE TITLE
Gas price should be fetched again when resend the transaction

### ISSUE THREAD

**Issue by invocamanman** [hermeznetwork/hermez-node#848]
## Rationale
Sometimes Gas Price could be affected by huge fluctuations, also sometimes some API could return some wrong value, as a result, the hermez-node will try to re-send a transaction with +10% gasPrice, but maybe a value so much higher could be required, leading to  a lot of time since it must resend a lot of transactions, as it happen here:
[40 transactions re-sent with higher gas Price. Can be checked in the `nonce` field](https://etherscan.io/tx/0x9ab2965b58ed866d578a85ac03de07e50e0b85ef5ef0805ea95da4ff2a0c037d)

## Implementation

I would suggest in this lines when the transaction is resubmitted with a higher gas Price:
[txManager L299](https://github.com/hermeznetwork/hermez-node/blob/develop/coordinator/txmanager.go#L299)
[txManager L304](https://github.com/hermeznetwork/hermez-node/blob/develop/coordinator/txmanager.go#L304)
To fetch again the gasPrice as it's done the first time [here](https://github.com/hermeznetwork/hermez-node/blob/develop/coordinator/txmanager.go#L132) and compare it with the `auth.GasPrice = addPerc(auth.GasPrice, 10)` and take the bigger value from both of them.

**Comment by jeffprestes** [comment]
Closing this issue as we are going to reafactor the gas price calculation to be more adjust to EIP-1559 model.
