### ISSUE TITLE
Expose total value locked via API

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#862]
## Rationale

It would be nice to expose via API:

- Total deposited amount per each token (and value in USD)
- Total value locked (sum of the total value in USD of all tokens)

## Implementation

- Synchronizer could do that by calling `balanceOf` on the SC, this gould give the total amount of tokens, since we already have the price in USD, once we have that it's trivial to implement

**Comment by jeffprestes** [comment]
We can return the total ether and other tokens locked to the Rollup Smart Contract. 
In another field we can return the value of it in USD.
However, the main information to be returned is the total ether and tokens balance.

**Comment by marioidival** [comment]
@arnaubennassar @jeffprestes What is the endpoint that the information should be exposed?

**Comment by jeffprestes** [comment]
As we have discussed we believe the state endpoint is the best place.

**Comment by marioidival** [comment]
This information can be found on https://etherscan.io/address/0xa68d85df56e733a06443306a095646317b5fa633#readProxyContract
