### ISSUE TITLE
GET /accounts not filtering propperly

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#865]
## Summary of Bug

The filter `hezEthereumAddress` doesn't work as expected, when using it the response includes accounts not related to the given Ethereum address.

### Expected Behavior

Only accounts that match the given address are returned by the endpoint

### Steps to Reproduce

Just do an API call using the mentioned filter such as [this one](https://api.hermez.io/v1/accounts?hez:0x42F870D97098d39D1535Cf8bF8f27e70f9c2616E).

**Comment by krlosMata** [comment]
The API following request: https://api.hermez.io/v1/accounts?hez:0x42F870D97098d39D1535Cf8bF8f27e70f9c2616E does not include filter name.
If `hezEthereumAddress` is added, API filters correctly: 
https://api.hermez.io/v1/accounts?hezEthereumAddress=hez:0x42F870D97098d39D1535Cf8bF8f27e70f9c2616E
