### ISSUE TITLE
MKR token fails synchronizing because it's not fully ERC20

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#868]
## Rationale

Some tokens have the name in bytes32 and make it fails
Adding the MKR token in the network will cause a bad synchronization problem, affected fields:
- Name
- Symbol
- Decimals

## Implementation

Since this is a very unique case (MKR was created before the ERC20 standard), we could have specific logic for this token only in the synchronizer

**Comment by jeffprestes** [comment]
Closing it as it does not follow the ERC-20 standard and this error only occurs during the token data import after it being added to rollup smart contract (what also happens once). It should be addressed as an incident and exception.
