### ISSUE TITLE
Typo in BAT Token listing

### ISSUE THREAD

**Issue by mmilenkovic** [hermeznetwork/hermez-node#874]
@druiz0992 commented on [Mon Jun 14 2021](https://github.com/hermeznetwork/batch-explorer/issues/250)

BAT token is described as `Basic Attention Toke` in https://explorer.hermez.io/tokens

---

@mmilenkovic commented on [Mon Jun 14 2021](https://github.com/hermeznetwork/batch-explorer/issues/250#issuecomment-860705165)

![Screenshot 2021-06-14 at 15.57.04.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/39b42251-a863-42b0-894a-d80db45ff492)

Typo comes from the API.

**Comment by jeffprestes** [comment]
Closing it as we don't have access to mainnet database. It should be addresses by @druiz0992 or @jbaylina
