### ISSUE TITLE
pending items in /tokens endpoint with limit value is giving wrong result

### ISSUE THREAD

**Issue by rauljareno** [hermeznetwork/hermez-node#888]
## Summary of Bug

When calling /tokens api with a limit value smaller that the number of supported tokens, the pendingItems response is not correct:

"pendingItems":18446744073709551614

https://api.hermez.io/v1/tokens?order=ASC&limit=20

### Expected Behavior

resulting pending items value

**Comment by Mikelle** [comment]
It's fixed and in develop branch - https://github.com/hermeznetwork/hermez-node/pull/881
