### ISSUE TITLE
Add option to get atomic transactions for the API

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#911]
## Rationale

There is no way for the users to fetch all the atomic transactions that belong to an atomic group which would be really handy.

## Implementation

- Add query filter in `GET /transacions-pool`: `atomicGroupId`
- Analyze if it's possible to get atomic related metadata from the synchronizer that allow this feature to be implemented also in `GET /transactions-history`, also the response from this endpoint doesn't include the `request` fields, so it's not possible to know if a forged transaction was atomic or not.

**Comment by invocamanman** [comment]
As an added information, the atomic transaction information cannot be synchronizer from ethereum, even it passes the circuit logic, it is not in the data availability of the ethereum call, and therefore, only the coordinator who forges the atomic transactions can have the corresponding information ( for example, which transaction are bonded)
