### ISSUE TITLE
Modify API format for atomic transactions

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#913]
## Rationale

Improve the API format for `POST /atomic-pool`

## Implementation

Depends on #905 

Implement this format:
```json
{
     "atomicGroupId": "0x...", // final format will be decided after closing #905, but it's very likely to be a hash just as the normal id for txs
     "transactions": [
          {
              " id": "0x....",
               // other fields, same as regular transactions
               "requestOffset": 1
          },
          {
               "id": "0x....",
               // other fields, same as regular transactions
               "requestOffset": 7
          }
     ]
}
```

As a reminder we will be following [this spec](https://docs.hermez.io/#/developers/protocol/hermez-protocol/circuits/circuits?id=rq-tx-verifier) for the `requestOffset` values

**Comment by jeffprestes** [comment]
Just to clarify, the **atomicGroupId** is going to be the hash of transaction->id 1, transaction->id 2, transaction->id 3, transaction->id n
