### ISSUE TITLE
Transactions filtered by account bug

### ISSUE THREAD

**Issue by laisolizq** [hermeznetwork/hermez-node#919]
## Summary of Bug

When we are on the page of an account, we can see the transactions that it has made.
For example: https://explorer.testnet.hermez.io/user-account/hez:IKnUt_GA9tcLMhXMTT-vMMQO27zW_RGaiAVAUZn0eAcs
But only the transactions filtered by account's BJJ are shown.
Filtered by BJJ: https://api.testnet.hermez.io/v1/transactions-history?BJJ=hez:IKnUt_GA9tcLMhXMTT-vMMQO27zW_RGaiAVAUZn0eAcs&&order=DESC
Filtered by Ethereum Address: https://api.testnet.hermez.io/v1/transactions-history?hezEthereumAddress=hez:0xB108B0245fd9C0316a22Dce8E3A6638625e5d989&&order=DESC

In the second case, the transactions with BJJ = `hez:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` are also shown. In the case of L1 transactions (except `createAccount`) it is not necessary to use the BJJ and therefore `hez:AAAA...` is used.

In the account information all transactions should be shown: a join of transactions filtered by ethereum address and filtered by BJJ.

**Comment by jeffprestes** [comment]
Closing it as it's going to be addressed by frontend team
