### ISSUE TITLE
/currencies endpoint is not handling encoded characters

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/hermez-node#940]
The `/currencies` API endpoint is not handling properly encoded `|` characters as it's returning a 404 error. In my opinion it would be better to replace this separator for the `symbols` query param with another one that doesn't need to be encoded, for example a `,`. Also the error code should be 400 if the URL is not correct instead of a 404.

![Captura de pantalla 2021-07-06 a las 11 39 46](https://user-images.githubusercontent.com/6737805/124578775-ce023a80-de4e-11eb-8644-5fcdcfc76e34.png)

**Comment by Mikelle** [comment]
It's not a bug, there was an error in the request URL (double currencies)
