### ISSUE TITLE
Start Hermez node as a service

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/hermez-node#954]
## Rationale

We are trying to simplify the start/stop of Hermez node so that it can be used as a Spot Instance in AWS. There are some
interactions between Hermez node and the non-postgres dB that may prevent this from happening. This request is to start
an investigation on what would be necessary.

**Comment by jeffprestes** [comment]
@mfcastellani let's discuss to create a linux service file for hermez-node (as reference: https://khanakia.medium.com/golang-running-a-go-binary-as-a-systemd-service-on-ubuntu-18-04-in-10-minutes-without-docker-e5a1e933bb7e )
