### ISSUE TITLE
Add a way to get the current HezNode URL

### ISSUE THREAD

**Issue by mfcastellani** [hermeznetwork/hermez-node#979]

**Comment by mfcastellani** [comment]
@arnaubennassar I opened this ticket related to your document, but after some research here I saw we already have this implemented. Please, take a look at the `examples/get-bootcoordinator-info/main.go` in `main` branch and let me know if this is what you expect.

**Comment by jeffprestes** [comment]
Closing it as it works well as @mfcastellani has explained. Please reopen the issue in case it would be needed more information.
