### ISSUE TITLE
Set a hardcoded Hermez node as client

### ISSUE THREAD

**Issue by mfcastellani** [hermeznetwork/hermez-node#982]
Option to set a “hardcoded” Hermez node as client. Keep in mind that a node is also used as explorer and it’s totally legit to use YOUR node not a “random” one. Also very important for testing new features that may be deployed only in a particular node (right now I’ll have to wait for the auction as the other nodes don’t have the endpoint I’m testing, probably it won’t work at first time and I could test without winning the auction until I can properly send the txs)

**Comment by jeffprestes** [comment]
@mfcastellani you meant have in the SDK methods an option to allow the user to set the hermez-node URL she wants to use?

**Comment by jeffprestes** [comment]
This issue can be closed because it is been handled by shared pool epic and the SDK selects the actual coordinator to send transactions.
