### ISSUE TITLE
Strategy for release cycles of the SDK

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#987]
## Rationale

We should define a way to coordinate releases for SDK / node. And do it in a way that makes obvious which versions of the SDK are compatible with node versions

EDIT: Ideally master/main branches of the node/sdk should include tagged versions only

**Comment by jeffprestes** [comment]
We're going to remove SDK dependencies in hermez-node and they're going to have different life cycles as sometimes improvements in one does not affect other project's code base.
