### ISSUE TITLE
AccountCreatonAuth signature is failing

### ISSUE THREAD

**Issue by arnaubennassar** [hermeznetwork/hermez-node#990]
## Summary of Bug

AccountCreatonAuth signature is failing on internaltestnet but not on testnet with same version of hermez-node (`v1.5.0-rc3`)

### System information

- Node version: `v*.*.*`
- OS: `Linux/OSX`

**Comment by jeffprestes** [comment]
Could you please provide the Ethereum account and the JSON you sent to /account-creation-authorization @AlbertoElias @elias-garcia  ? This is going to help us a lot to debug the error

**Comment by AlbertoElias** [comment]
An example request which includes the Eth address:

```
{
bjj: "hez:GRjmq1d0tyeFxtEsTOAzFFc5Vl2aTKXdVuLRQiHzwJqK",
hezEthereumAddress: "hez:0x1f2E38C05195bc75d40B80a0bcEe56a66134BF15",
signature: "0x0b67dc1da91f2b714208795e26240e5ca98d7d910b5f5a40f344d6d8e7124843322fbc5d32f319b12c4f4c64bc926d38a46497b47d6838ebec147c5468ca3e0c1b"
}
```

**Comment by jeffprestes** [comment]
After some tests using Go SDK the service looks like fine after 1.6 version
